---
- hosts: localhost

  vars:
    domain_name: mydomain-com
    domain_workdir: "host_files/{{ domain_name }}"

    ssl:
      country: CA
      state: Ontario
      locality: Warkworth
      organization: Kautkur
      organization_unit: Hicksville
      common_name: "{{ domain_name }}"
    sans:
      - www.mydomain.com
      - www.mydomein.com
      - www.anotheronetoo.com

  tasks:
  - name: Template a file to /tmp/openssl.conf
    template:
      src: openssl.conf.j2
      dest: /tmp/openssl.conf
      mode: '0644'

  - name: Create a directory if it does not exist
    file:
      path: group_files/all
      state: directory
      mode: '0755'

  - name: Check that the rootCA.key exists
    stat:
      path: group_files/all/rootCA.key
    register: stat_result

  - name: create private key
    command: openssl genrsa -out group_files/all/rootCA.key 4096
    when: not stat_result.stat.exists

  - name: create self-signed CA
    command: openssl req -x509 -new -nodes -key group_files/all/rootCA.key \
      -config /tmp/openssl.conf \
      -sha256 -days 1024 -out group_files/all/rootCA.crt
      
  - name: Create a directory if it does not exist
    file:
      path: "{{ domain_workdir }}"
      state: directory
      mode: '0755'

  - name: generate certificate key
    command: "openssl genrsa -out {{ domain_workdir }}/mydomain.com.key 2048"

  - name: generate CSR
    command: openssl req -new -sha256 \
      -key "{{ domain_workdir }}/mydomain.com.key" \
      -config /tmp/openssl.conf \
      -out "{{ domain_workdir }}/mydomain.com.csr"

  - name: sign CSR
    command: openssl x509 -req \
      -extensions v3_req \
      -extfile /tmp/openssl.conf -days 120 \
      -in "{{ domain_workdir }}/mydomain.com.csr" \
      -CA group_files/all/rootCA.crt \
      -CAkey group_files/all/rootCA.key -CAcreateserial \
      -out "{{ domain_workdir }}/mydomain.com.crt" -sha256

